version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      # Volume persistente para o banco de dados SQLite e referência ao volume nomeado
      - db_data:/app/db
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
    # command: ["sh", "-c", "chmod +x /app/docker-entrypoint.sh && /app/docker-entrypoint.sh"]


  # Ele garante que os dados do banco de dados sejam mantidos persistentemente
volumes:
  # Declaração explícita do volume nomeado
  db_data: